// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: geolocationService.proto

package net.vbunova.grpc;

public final class GeolocationService {
  private GeolocationService() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface LocationRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:LocationRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string lat = 1;</code>
     * @return The lat.
     */
    java.lang.String getLat();
    /**
     * <code>string lat = 1;</code>
     * @return The bytes for lat.
     */
    com.google.protobuf.ByteString
        getLatBytes();

    /**
     * <code>string lon = 2;</code>
     * @return The lon.
     */
    java.lang.String getLon();
    /**
     * <code>string lon = 2;</code>
     * @return The bytes for lon.
     */
    com.google.protobuf.ByteString
        getLonBytes();
  }
  /**
   * Protobuf type {@code LocationRequest}
   */
  public  static final class LocationRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:LocationRequest)
      LocationRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use LocationRequest.newBuilder() to construct.
    private LocationRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private LocationRequest() {
      lat_ = "";
      lon_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new LocationRequest();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private LocationRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              lat_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              lon_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return net.vbunova.grpc.GeolocationService.internal_static_LocationRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return net.vbunova.grpc.GeolocationService.internal_static_LocationRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              net.vbunova.grpc.GeolocationService.LocationRequest.class, net.vbunova.grpc.GeolocationService.LocationRequest.Builder.class);
    }

    public static final int LAT_FIELD_NUMBER = 1;
    private volatile java.lang.Object lat_;
    /**
     * <code>string lat = 1;</code>
     * @return The lat.
     */
    public java.lang.String getLat() {
      java.lang.Object ref = lat_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        lat_ = s;
        return s;
      }
    }
    /**
     * <code>string lat = 1;</code>
     * @return The bytes for lat.
     */
    public com.google.protobuf.ByteString
        getLatBytes() {
      java.lang.Object ref = lat_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        lat_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int LON_FIELD_NUMBER = 2;
    private volatile java.lang.Object lon_;
    /**
     * <code>string lon = 2;</code>
     * @return The lon.
     */
    public java.lang.String getLon() {
      java.lang.Object ref = lon_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        lon_ = s;
        return s;
      }
    }
    /**
     * <code>string lon = 2;</code>
     * @return The bytes for lon.
     */
    public com.google.protobuf.ByteString
        getLonBytes() {
      java.lang.Object ref = lon_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        lon_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getLatBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, lat_);
      }
      if (!getLonBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, lon_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getLatBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, lat_);
      }
      if (!getLonBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, lon_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof net.vbunova.grpc.GeolocationService.LocationRequest)) {
        return super.equals(obj);
      }
      net.vbunova.grpc.GeolocationService.LocationRequest other = (net.vbunova.grpc.GeolocationService.LocationRequest) obj;

      if (!getLat()
          .equals(other.getLat())) return false;
      if (!getLon()
          .equals(other.getLon())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + LAT_FIELD_NUMBER;
      hash = (53 * hash) + getLat().hashCode();
      hash = (37 * hash) + LON_FIELD_NUMBER;
      hash = (53 * hash) + getLon().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static net.vbunova.grpc.GeolocationService.LocationRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static net.vbunova.grpc.GeolocationService.LocationRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static net.vbunova.grpc.GeolocationService.LocationRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static net.vbunova.grpc.GeolocationService.LocationRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static net.vbunova.grpc.GeolocationService.LocationRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static net.vbunova.grpc.GeolocationService.LocationRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static net.vbunova.grpc.GeolocationService.LocationRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static net.vbunova.grpc.GeolocationService.LocationRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static net.vbunova.grpc.GeolocationService.LocationRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static net.vbunova.grpc.GeolocationService.LocationRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static net.vbunova.grpc.GeolocationService.LocationRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static net.vbunova.grpc.GeolocationService.LocationRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(net.vbunova.grpc.GeolocationService.LocationRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code LocationRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:LocationRequest)
        net.vbunova.grpc.GeolocationService.LocationRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return net.vbunova.grpc.GeolocationService.internal_static_LocationRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return net.vbunova.grpc.GeolocationService.internal_static_LocationRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                net.vbunova.grpc.GeolocationService.LocationRequest.class, net.vbunova.grpc.GeolocationService.LocationRequest.Builder.class);
      }

      // Construct using net.vbunova.grpc.GeolocationService.LocationRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        lat_ = "";

        lon_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return net.vbunova.grpc.GeolocationService.internal_static_LocationRequest_descriptor;
      }

      @java.lang.Override
      public net.vbunova.grpc.GeolocationService.LocationRequest getDefaultInstanceForType() {
        return net.vbunova.grpc.GeolocationService.LocationRequest.getDefaultInstance();
      }

      @java.lang.Override
      public net.vbunova.grpc.GeolocationService.LocationRequest build() {
        net.vbunova.grpc.GeolocationService.LocationRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public net.vbunova.grpc.GeolocationService.LocationRequest buildPartial() {
        net.vbunova.grpc.GeolocationService.LocationRequest result = new net.vbunova.grpc.GeolocationService.LocationRequest(this);
        result.lat_ = lat_;
        result.lon_ = lon_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof net.vbunova.grpc.GeolocationService.LocationRequest) {
          return mergeFrom((net.vbunova.grpc.GeolocationService.LocationRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(net.vbunova.grpc.GeolocationService.LocationRequest other) {
        if (other == net.vbunova.grpc.GeolocationService.LocationRequest.getDefaultInstance()) return this;
        if (!other.getLat().isEmpty()) {
          lat_ = other.lat_;
          onChanged();
        }
        if (!other.getLon().isEmpty()) {
          lon_ = other.lon_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        net.vbunova.grpc.GeolocationService.LocationRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (net.vbunova.grpc.GeolocationService.LocationRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object lat_ = "";
      /**
       * <code>string lat = 1;</code>
       * @return The lat.
       */
      public java.lang.String getLat() {
        java.lang.Object ref = lat_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          lat_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string lat = 1;</code>
       * @return The bytes for lat.
       */
      public com.google.protobuf.ByteString
          getLatBytes() {
        java.lang.Object ref = lat_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          lat_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string lat = 1;</code>
       * @param value The lat to set.
       * @return This builder for chaining.
       */
      public Builder setLat(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        lat_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string lat = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearLat() {
        
        lat_ = getDefaultInstance().getLat();
        onChanged();
        return this;
      }
      /**
       * <code>string lat = 1;</code>
       * @param value The bytes for lat to set.
       * @return This builder for chaining.
       */
      public Builder setLatBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        lat_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object lon_ = "";
      /**
       * <code>string lon = 2;</code>
       * @return The lon.
       */
      public java.lang.String getLon() {
        java.lang.Object ref = lon_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          lon_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string lon = 2;</code>
       * @return The bytes for lon.
       */
      public com.google.protobuf.ByteString
          getLonBytes() {
        java.lang.Object ref = lon_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          lon_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string lon = 2;</code>
       * @param value The lon to set.
       * @return This builder for chaining.
       */
      public Builder setLon(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        lon_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string lon = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearLon() {
        
        lon_ = getDefaultInstance().getLon();
        onChanged();
        return this;
      }
      /**
       * <code>string lon = 2;</code>
       * @param value The bytes for lon to set.
       * @return This builder for chaining.
       */
      public Builder setLonBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        lon_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:LocationRequest)
    }

    // @@protoc_insertion_point(class_scope:LocationRequest)
    private static final net.vbunova.grpc.GeolocationService.LocationRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new net.vbunova.grpc.GeolocationService.LocationRequest();
    }

    public static net.vbunova.grpc.GeolocationService.LocationRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<LocationRequest>
        PARSER = new com.google.protobuf.AbstractParser<LocationRequest>() {
      @java.lang.Override
      public LocationRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new LocationRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<LocationRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<LocationRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public net.vbunova.grpc.GeolocationService.LocationRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface LocationRequestResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:LocationRequestResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 locationId = 1;</code>
     * @return The locationId.
     */
    int getLocationId();
  }
  /**
   * Protobuf type {@code LocationRequestResponse}
   */
  public  static final class LocationRequestResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:LocationRequestResponse)
      LocationRequestResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use LocationRequestResponse.newBuilder() to construct.
    private LocationRequestResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private LocationRequestResponse() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new LocationRequestResponse();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private LocationRequestResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              locationId_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return net.vbunova.grpc.GeolocationService.internal_static_LocationRequestResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return net.vbunova.grpc.GeolocationService.internal_static_LocationRequestResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              net.vbunova.grpc.GeolocationService.LocationRequestResponse.class, net.vbunova.grpc.GeolocationService.LocationRequestResponse.Builder.class);
    }

    public static final int LOCATIONID_FIELD_NUMBER = 1;
    private int locationId_;
    /**
     * <code>int32 locationId = 1;</code>
     * @return The locationId.
     */
    public int getLocationId() {
      return locationId_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (locationId_ != 0) {
        output.writeInt32(1, locationId_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (locationId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, locationId_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof net.vbunova.grpc.GeolocationService.LocationRequestResponse)) {
        return super.equals(obj);
      }
      net.vbunova.grpc.GeolocationService.LocationRequestResponse other = (net.vbunova.grpc.GeolocationService.LocationRequestResponse) obj;

      if (getLocationId()
          != other.getLocationId()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + LOCATIONID_FIELD_NUMBER;
      hash = (53 * hash) + getLocationId();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static net.vbunova.grpc.GeolocationService.LocationRequestResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static net.vbunova.grpc.GeolocationService.LocationRequestResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static net.vbunova.grpc.GeolocationService.LocationRequestResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static net.vbunova.grpc.GeolocationService.LocationRequestResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static net.vbunova.grpc.GeolocationService.LocationRequestResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static net.vbunova.grpc.GeolocationService.LocationRequestResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static net.vbunova.grpc.GeolocationService.LocationRequestResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static net.vbunova.grpc.GeolocationService.LocationRequestResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static net.vbunova.grpc.GeolocationService.LocationRequestResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static net.vbunova.grpc.GeolocationService.LocationRequestResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static net.vbunova.grpc.GeolocationService.LocationRequestResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static net.vbunova.grpc.GeolocationService.LocationRequestResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(net.vbunova.grpc.GeolocationService.LocationRequestResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code LocationRequestResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:LocationRequestResponse)
        net.vbunova.grpc.GeolocationService.LocationRequestResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return net.vbunova.grpc.GeolocationService.internal_static_LocationRequestResponse_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return net.vbunova.grpc.GeolocationService.internal_static_LocationRequestResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                net.vbunova.grpc.GeolocationService.LocationRequestResponse.class, net.vbunova.grpc.GeolocationService.LocationRequestResponse.Builder.class);
      }

      // Construct using net.vbunova.grpc.GeolocationService.LocationRequestResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        locationId_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return net.vbunova.grpc.GeolocationService.internal_static_LocationRequestResponse_descriptor;
      }

      @java.lang.Override
      public net.vbunova.grpc.GeolocationService.LocationRequestResponse getDefaultInstanceForType() {
        return net.vbunova.grpc.GeolocationService.LocationRequestResponse.getDefaultInstance();
      }

      @java.lang.Override
      public net.vbunova.grpc.GeolocationService.LocationRequestResponse build() {
        net.vbunova.grpc.GeolocationService.LocationRequestResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public net.vbunova.grpc.GeolocationService.LocationRequestResponse buildPartial() {
        net.vbunova.grpc.GeolocationService.LocationRequestResponse result = new net.vbunova.grpc.GeolocationService.LocationRequestResponse(this);
        result.locationId_ = locationId_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof net.vbunova.grpc.GeolocationService.LocationRequestResponse) {
          return mergeFrom((net.vbunova.grpc.GeolocationService.LocationRequestResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(net.vbunova.grpc.GeolocationService.LocationRequestResponse other) {
        if (other == net.vbunova.grpc.GeolocationService.LocationRequestResponse.getDefaultInstance()) return this;
        if (other.getLocationId() != 0) {
          setLocationId(other.getLocationId());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        net.vbunova.grpc.GeolocationService.LocationRequestResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (net.vbunova.grpc.GeolocationService.LocationRequestResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int locationId_ ;
      /**
       * <code>int32 locationId = 1;</code>
       * @return The locationId.
       */
      public int getLocationId() {
        return locationId_;
      }
      /**
       * <code>int32 locationId = 1;</code>
       * @param value The locationId to set.
       * @return This builder for chaining.
       */
      public Builder setLocationId(int value) {
        
        locationId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 locationId = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearLocationId() {
        
        locationId_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:LocationRequestResponse)
    }

    // @@protoc_insertion_point(class_scope:LocationRequestResponse)
    private static final net.vbunova.grpc.GeolocationService.LocationRequestResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new net.vbunova.grpc.GeolocationService.LocationRequestResponse();
    }

    public static net.vbunova.grpc.GeolocationService.LocationRequestResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<LocationRequestResponse>
        PARSER = new com.google.protobuf.AbstractParser<LocationRequestResponse>() {
      @java.lang.Override
      public LocationRequestResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new LocationRequestResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<LocationRequestResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<LocationRequestResponse> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public net.vbunova.grpc.GeolocationService.LocationRequestResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_LocationRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_LocationRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_LocationRequestResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_LocationRequestResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\030geolocationService.proto\"+\n\017LocationRe" +
      "quest\022\013\n\003lat\030\001 \001(\t\022\013\n\003lon\030\002 \001(\t\"-\n\027Locat" +
      "ionRequestResponse\022\022\n\nlocationId\030\001 \001(\0052O" +
      "\n\022geolocationService\0229\n\013getLocation\022\020.Lo" +
      "cationRequest\032\030.LocationRequestResponseB" +
      "\022\n\020net.vbunova.grpcb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_LocationRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_LocationRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_LocationRequest_descriptor,
        new java.lang.String[] { "Lat", "Lon", });
    internal_static_LocationRequestResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_LocationRequestResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_LocationRequestResponse_descriptor,
        new java.lang.String[] { "LocationId", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
