// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: streetLightService.proto

package net.vbunova.grpc;

public final class StreetLightService {
  private StreetLightService() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ActivateLightsRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ActivateLightsRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string lat = 1;</code>
     * @return The lat.
     */
    java.lang.String getLat();
    /**
     * <code>string lat = 1;</code>
     * @return The bytes for lat.
     */
    com.google.protobuf.ByteString
        getLatBytes();

    /**
     * <code>string lon = 2;</code>
     * @return The lon.
     */
    java.lang.String getLon();
    /**
     * <code>string lon = 2;</code>
     * @return The bytes for lon.
     */
    com.google.protobuf.ByteString
        getLonBytes();
  }
  /**
   * Protobuf type {@code ActivateLightsRequest}
   */
  public  static final class ActivateLightsRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:ActivateLightsRequest)
      ActivateLightsRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ActivateLightsRequest.newBuilder() to construct.
    private ActivateLightsRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ActivateLightsRequest() {
      lat_ = "";
      lon_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new ActivateLightsRequest();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ActivateLightsRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              lat_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              lon_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return net.vbunova.grpc.StreetLightService.internal_static_ActivateLightsRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return net.vbunova.grpc.StreetLightService.internal_static_ActivateLightsRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              net.vbunova.grpc.StreetLightService.ActivateLightsRequest.class, net.vbunova.grpc.StreetLightService.ActivateLightsRequest.Builder.class);
    }

    public static final int LAT_FIELD_NUMBER = 1;
    private volatile java.lang.Object lat_;
    /**
     * <code>string lat = 1;</code>
     * @return The lat.
     */
    public java.lang.String getLat() {
      java.lang.Object ref = lat_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        lat_ = s;
        return s;
      }
    }
    /**
     * <code>string lat = 1;</code>
     * @return The bytes for lat.
     */
    public com.google.protobuf.ByteString
        getLatBytes() {
      java.lang.Object ref = lat_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        lat_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int LON_FIELD_NUMBER = 2;
    private volatile java.lang.Object lon_;
    /**
     * <code>string lon = 2;</code>
     * @return The lon.
     */
    public java.lang.String getLon() {
      java.lang.Object ref = lon_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        lon_ = s;
        return s;
      }
    }
    /**
     * <code>string lon = 2;</code>
     * @return The bytes for lon.
     */
    public com.google.protobuf.ByteString
        getLonBytes() {
      java.lang.Object ref = lon_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        lon_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getLatBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, lat_);
      }
      if (!getLonBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, lon_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getLatBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, lat_);
      }
      if (!getLonBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, lon_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof net.vbunova.grpc.StreetLightService.ActivateLightsRequest)) {
        return super.equals(obj);
      }
      net.vbunova.grpc.StreetLightService.ActivateLightsRequest other = (net.vbunova.grpc.StreetLightService.ActivateLightsRequest) obj;

      if (!getLat()
          .equals(other.getLat())) return false;
      if (!getLon()
          .equals(other.getLon())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + LAT_FIELD_NUMBER;
      hash = (53 * hash) + getLat().hashCode();
      hash = (37 * hash) + LON_FIELD_NUMBER;
      hash = (53 * hash) + getLon().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static net.vbunova.grpc.StreetLightService.ActivateLightsRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static net.vbunova.grpc.StreetLightService.ActivateLightsRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static net.vbunova.grpc.StreetLightService.ActivateLightsRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static net.vbunova.grpc.StreetLightService.ActivateLightsRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static net.vbunova.grpc.StreetLightService.ActivateLightsRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static net.vbunova.grpc.StreetLightService.ActivateLightsRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static net.vbunova.grpc.StreetLightService.ActivateLightsRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static net.vbunova.grpc.StreetLightService.ActivateLightsRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static net.vbunova.grpc.StreetLightService.ActivateLightsRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static net.vbunova.grpc.StreetLightService.ActivateLightsRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static net.vbunova.grpc.StreetLightService.ActivateLightsRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static net.vbunova.grpc.StreetLightService.ActivateLightsRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(net.vbunova.grpc.StreetLightService.ActivateLightsRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ActivateLightsRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ActivateLightsRequest)
        net.vbunova.grpc.StreetLightService.ActivateLightsRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return net.vbunova.grpc.StreetLightService.internal_static_ActivateLightsRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return net.vbunova.grpc.StreetLightService.internal_static_ActivateLightsRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                net.vbunova.grpc.StreetLightService.ActivateLightsRequest.class, net.vbunova.grpc.StreetLightService.ActivateLightsRequest.Builder.class);
      }

      // Construct using net.vbunova.grpc.StreetLightService.ActivateLightsRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        lat_ = "";

        lon_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return net.vbunova.grpc.StreetLightService.internal_static_ActivateLightsRequest_descriptor;
      }

      @java.lang.Override
      public net.vbunova.grpc.StreetLightService.ActivateLightsRequest getDefaultInstanceForType() {
        return net.vbunova.grpc.StreetLightService.ActivateLightsRequest.getDefaultInstance();
      }

      @java.lang.Override
      public net.vbunova.grpc.StreetLightService.ActivateLightsRequest build() {
        net.vbunova.grpc.StreetLightService.ActivateLightsRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public net.vbunova.grpc.StreetLightService.ActivateLightsRequest buildPartial() {
        net.vbunova.grpc.StreetLightService.ActivateLightsRequest result = new net.vbunova.grpc.StreetLightService.ActivateLightsRequest(this);
        result.lat_ = lat_;
        result.lon_ = lon_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof net.vbunova.grpc.StreetLightService.ActivateLightsRequest) {
          return mergeFrom((net.vbunova.grpc.StreetLightService.ActivateLightsRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(net.vbunova.grpc.StreetLightService.ActivateLightsRequest other) {
        if (other == net.vbunova.grpc.StreetLightService.ActivateLightsRequest.getDefaultInstance()) return this;
        if (!other.getLat().isEmpty()) {
          lat_ = other.lat_;
          onChanged();
        }
        if (!other.getLon().isEmpty()) {
          lon_ = other.lon_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        net.vbunova.grpc.StreetLightService.ActivateLightsRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (net.vbunova.grpc.StreetLightService.ActivateLightsRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object lat_ = "";
      /**
       * <code>string lat = 1;</code>
       * @return The lat.
       */
      public java.lang.String getLat() {
        java.lang.Object ref = lat_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          lat_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string lat = 1;</code>
       * @return The bytes for lat.
       */
      public com.google.protobuf.ByteString
          getLatBytes() {
        java.lang.Object ref = lat_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          lat_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string lat = 1;</code>
       * @param value The lat to set.
       * @return This builder for chaining.
       */
      public Builder setLat(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        lat_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string lat = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearLat() {
        
        lat_ = getDefaultInstance().getLat();
        onChanged();
        return this;
      }
      /**
       * <code>string lat = 1;</code>
       * @param value The bytes for lat to set.
       * @return This builder for chaining.
       */
      public Builder setLatBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        lat_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object lon_ = "";
      /**
       * <code>string lon = 2;</code>
       * @return The lon.
       */
      public java.lang.String getLon() {
        java.lang.Object ref = lon_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          lon_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string lon = 2;</code>
       * @return The bytes for lon.
       */
      public com.google.protobuf.ByteString
          getLonBytes() {
        java.lang.Object ref = lon_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          lon_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string lon = 2;</code>
       * @param value The lon to set.
       * @return This builder for chaining.
       */
      public Builder setLon(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        lon_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string lon = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearLon() {
        
        lon_ = getDefaultInstance().getLon();
        onChanged();
        return this;
      }
      /**
       * <code>string lon = 2;</code>
       * @param value The bytes for lon to set.
       * @return This builder for chaining.
       */
      public Builder setLonBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        lon_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:ActivateLightsRequest)
    }

    // @@protoc_insertion_point(class_scope:ActivateLightsRequest)
    private static final net.vbunova.grpc.StreetLightService.ActivateLightsRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new net.vbunova.grpc.StreetLightService.ActivateLightsRequest();
    }

    public static net.vbunova.grpc.StreetLightService.ActivateLightsRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ActivateLightsRequest>
        PARSER = new com.google.protobuf.AbstractParser<ActivateLightsRequest>() {
      @java.lang.Override
      public ActivateLightsRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ActivateLightsRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ActivateLightsRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ActivateLightsRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public net.vbunova.grpc.StreetLightService.ActivateLightsRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ActivateLightsResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ActivateLightsResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>bool status = 1;</code>
     * @return The status.
     */
    boolean getStatus();
  }
  /**
   * Protobuf type {@code ActivateLightsResponse}
   */
  public  static final class ActivateLightsResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:ActivateLightsResponse)
      ActivateLightsResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ActivateLightsResponse.newBuilder() to construct.
    private ActivateLightsResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ActivateLightsResponse() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new ActivateLightsResponse();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ActivateLightsResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              status_ = input.readBool();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return net.vbunova.grpc.StreetLightService.internal_static_ActivateLightsResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return net.vbunova.grpc.StreetLightService.internal_static_ActivateLightsResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              net.vbunova.grpc.StreetLightService.ActivateLightsResponse.class, net.vbunova.grpc.StreetLightService.ActivateLightsResponse.Builder.class);
    }

    public static final int STATUS_FIELD_NUMBER = 1;
    private boolean status_;
    /**
     * <code>bool status = 1;</code>
     * @return The status.
     */
    public boolean getStatus() {
      return status_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (status_ != false) {
        output.writeBool(1, status_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (status_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(1, status_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof net.vbunova.grpc.StreetLightService.ActivateLightsResponse)) {
        return super.equals(obj);
      }
      net.vbunova.grpc.StreetLightService.ActivateLightsResponse other = (net.vbunova.grpc.StreetLightService.ActivateLightsResponse) obj;

      if (getStatus()
          != other.getStatus()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + STATUS_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getStatus());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static net.vbunova.grpc.StreetLightService.ActivateLightsResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static net.vbunova.grpc.StreetLightService.ActivateLightsResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static net.vbunova.grpc.StreetLightService.ActivateLightsResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static net.vbunova.grpc.StreetLightService.ActivateLightsResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static net.vbunova.grpc.StreetLightService.ActivateLightsResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static net.vbunova.grpc.StreetLightService.ActivateLightsResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static net.vbunova.grpc.StreetLightService.ActivateLightsResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static net.vbunova.grpc.StreetLightService.ActivateLightsResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static net.vbunova.grpc.StreetLightService.ActivateLightsResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static net.vbunova.grpc.StreetLightService.ActivateLightsResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static net.vbunova.grpc.StreetLightService.ActivateLightsResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static net.vbunova.grpc.StreetLightService.ActivateLightsResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(net.vbunova.grpc.StreetLightService.ActivateLightsResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ActivateLightsResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ActivateLightsResponse)
        net.vbunova.grpc.StreetLightService.ActivateLightsResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return net.vbunova.grpc.StreetLightService.internal_static_ActivateLightsResponse_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return net.vbunova.grpc.StreetLightService.internal_static_ActivateLightsResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                net.vbunova.grpc.StreetLightService.ActivateLightsResponse.class, net.vbunova.grpc.StreetLightService.ActivateLightsResponse.Builder.class);
      }

      // Construct using net.vbunova.grpc.StreetLightService.ActivateLightsResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        status_ = false;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return net.vbunova.grpc.StreetLightService.internal_static_ActivateLightsResponse_descriptor;
      }

      @java.lang.Override
      public net.vbunova.grpc.StreetLightService.ActivateLightsResponse getDefaultInstanceForType() {
        return net.vbunova.grpc.StreetLightService.ActivateLightsResponse.getDefaultInstance();
      }

      @java.lang.Override
      public net.vbunova.grpc.StreetLightService.ActivateLightsResponse build() {
        net.vbunova.grpc.StreetLightService.ActivateLightsResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public net.vbunova.grpc.StreetLightService.ActivateLightsResponse buildPartial() {
        net.vbunova.grpc.StreetLightService.ActivateLightsResponse result = new net.vbunova.grpc.StreetLightService.ActivateLightsResponse(this);
        result.status_ = status_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof net.vbunova.grpc.StreetLightService.ActivateLightsResponse) {
          return mergeFrom((net.vbunova.grpc.StreetLightService.ActivateLightsResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(net.vbunova.grpc.StreetLightService.ActivateLightsResponse other) {
        if (other == net.vbunova.grpc.StreetLightService.ActivateLightsResponse.getDefaultInstance()) return this;
        if (other.getStatus() != false) {
          setStatus(other.getStatus());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        net.vbunova.grpc.StreetLightService.ActivateLightsResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (net.vbunova.grpc.StreetLightService.ActivateLightsResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private boolean status_ ;
      /**
       * <code>bool status = 1;</code>
       * @return The status.
       */
      public boolean getStatus() {
        return status_;
      }
      /**
       * <code>bool status = 1;</code>
       * @param value The status to set.
       * @return This builder for chaining.
       */
      public Builder setStatus(boolean value) {
        
        status_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool status = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearStatus() {
        
        status_ = false;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:ActivateLightsResponse)
    }

    // @@protoc_insertion_point(class_scope:ActivateLightsResponse)
    private static final net.vbunova.grpc.StreetLightService.ActivateLightsResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new net.vbunova.grpc.StreetLightService.ActivateLightsResponse();
    }

    public static net.vbunova.grpc.StreetLightService.ActivateLightsResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ActivateLightsResponse>
        PARSER = new com.google.protobuf.AbstractParser<ActivateLightsResponse>() {
      @java.lang.Override
      public ActivateLightsResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ActivateLightsResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ActivateLightsResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ActivateLightsResponse> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public net.vbunova.grpc.StreetLightService.ActivateLightsResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ActivateLightsRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ActivateLightsRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ActivateLightsResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ActivateLightsResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\030streetLightService.proto\"1\n\025ActivateLi" +
      "ghtsRequest\022\013\n\003lat\030\001 \001(\t\022\013\n\003lon\030\002 \001(\t\"(\n" +
      "\026ActivateLightsResponse\022\016\n\006status\030\001 \001(\0102" +
      "W\n\022streetLightService\022A\n\016activateLights\022" +
      "\026.ActivateLightsRequest\032\027.ActivateLights" +
      "ResponseB\022\n\020net.vbunova.grpcb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_ActivateLightsRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ActivateLightsRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ActivateLightsRequest_descriptor,
        new java.lang.String[] { "Lat", "Lon", });
    internal_static_ActivateLightsResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_ActivateLightsResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ActivateLightsResponse_descriptor,
        new java.lang.String[] { "Status", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
