// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: vehicleService.proto

package net.vbunova.grpc;

public final class VehicleService {
  private VehicleService() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface VehicleInformationRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:VehicleInformationRequest)
      com.google.protobuf.MessageOrBuilder {
  }
  /**
   * Protobuf type {@code VehicleInformationRequest}
   */
  public  static final class VehicleInformationRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:VehicleInformationRequest)
      VehicleInformationRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use VehicleInformationRequest.newBuilder() to construct.
    private VehicleInformationRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private VehicleInformationRequest() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new VehicleInformationRequest();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private VehicleInformationRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return net.vbunova.grpc.VehicleService.internal_static_VehicleInformationRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return net.vbunova.grpc.VehicleService.internal_static_VehicleInformationRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              net.vbunova.grpc.VehicleService.VehicleInformationRequest.class, net.vbunova.grpc.VehicleService.VehicleInformationRequest.Builder.class);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof net.vbunova.grpc.VehicleService.VehicleInformationRequest)) {
        return super.equals(obj);
      }
      net.vbunova.grpc.VehicleService.VehicleInformationRequest other = (net.vbunova.grpc.VehicleService.VehicleInformationRequest) obj;

      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static net.vbunova.grpc.VehicleService.VehicleInformationRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static net.vbunova.grpc.VehicleService.VehicleInformationRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static net.vbunova.grpc.VehicleService.VehicleInformationRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static net.vbunova.grpc.VehicleService.VehicleInformationRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static net.vbunova.grpc.VehicleService.VehicleInformationRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static net.vbunova.grpc.VehicleService.VehicleInformationRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static net.vbunova.grpc.VehicleService.VehicleInformationRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static net.vbunova.grpc.VehicleService.VehicleInformationRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static net.vbunova.grpc.VehicleService.VehicleInformationRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static net.vbunova.grpc.VehicleService.VehicleInformationRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static net.vbunova.grpc.VehicleService.VehicleInformationRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static net.vbunova.grpc.VehicleService.VehicleInformationRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(net.vbunova.grpc.VehicleService.VehicleInformationRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code VehicleInformationRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:VehicleInformationRequest)
        net.vbunova.grpc.VehicleService.VehicleInformationRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return net.vbunova.grpc.VehicleService.internal_static_VehicleInformationRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return net.vbunova.grpc.VehicleService.internal_static_VehicleInformationRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                net.vbunova.grpc.VehicleService.VehicleInformationRequest.class, net.vbunova.grpc.VehicleService.VehicleInformationRequest.Builder.class);
      }

      // Construct using net.vbunova.grpc.VehicleService.VehicleInformationRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return net.vbunova.grpc.VehicleService.internal_static_VehicleInformationRequest_descriptor;
      }

      @java.lang.Override
      public net.vbunova.grpc.VehicleService.VehicleInformationRequest getDefaultInstanceForType() {
        return net.vbunova.grpc.VehicleService.VehicleInformationRequest.getDefaultInstance();
      }

      @java.lang.Override
      public net.vbunova.grpc.VehicleService.VehicleInformationRequest build() {
        net.vbunova.grpc.VehicleService.VehicleInformationRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public net.vbunova.grpc.VehicleService.VehicleInformationRequest buildPartial() {
        net.vbunova.grpc.VehicleService.VehicleInformationRequest result = new net.vbunova.grpc.VehicleService.VehicleInformationRequest(this);
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof net.vbunova.grpc.VehicleService.VehicleInformationRequest) {
          return mergeFrom((net.vbunova.grpc.VehicleService.VehicleInformationRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(net.vbunova.grpc.VehicleService.VehicleInformationRequest other) {
        if (other == net.vbunova.grpc.VehicleService.VehicleInformationRequest.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        net.vbunova.grpc.VehicleService.VehicleInformationRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (net.vbunova.grpc.VehicleService.VehicleInformationRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:VehicleInformationRequest)
    }

    // @@protoc_insertion_point(class_scope:VehicleInformationRequest)
    private static final net.vbunova.grpc.VehicleService.VehicleInformationRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new net.vbunova.grpc.VehicleService.VehicleInformationRequest();
    }

    public static net.vbunova.grpc.VehicleService.VehicleInformationRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<VehicleInformationRequest>
        PARSER = new com.google.protobuf.AbstractParser<VehicleInformationRequest>() {
      @java.lang.Override
      public VehicleInformationRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new VehicleInformationRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<VehicleInformationRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<VehicleInformationRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public net.vbunova.grpc.VehicleService.VehicleInformationRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface VehicleInformationResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:VehicleInformationResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 vehicleId = 1;</code>
     * @return The vehicleId.
     */
    int getVehicleId();

    /**
     * <code>string metadata = 2;</code>
     * @return The metadata.
     */
    java.lang.String getMetadata();
    /**
     * <code>string metadata = 2;</code>
     * @return The bytes for metadata.
     */
    com.google.protobuf.ByteString
        getMetadataBytes();
  }
  /**
   * Protobuf type {@code VehicleInformationResponse}
   */
  public  static final class VehicleInformationResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:VehicleInformationResponse)
      VehicleInformationResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use VehicleInformationResponse.newBuilder() to construct.
    private VehicleInformationResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private VehicleInformationResponse() {
      metadata_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new VehicleInformationResponse();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private VehicleInformationResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              vehicleId_ = input.readInt32();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              metadata_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return net.vbunova.grpc.VehicleService.internal_static_VehicleInformationResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return net.vbunova.grpc.VehicleService.internal_static_VehicleInformationResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              net.vbunova.grpc.VehicleService.VehicleInformationResponse.class, net.vbunova.grpc.VehicleService.VehicleInformationResponse.Builder.class);
    }

    public static final int VEHICLEID_FIELD_NUMBER = 1;
    private int vehicleId_;
    /**
     * <code>int32 vehicleId = 1;</code>
     * @return The vehicleId.
     */
    public int getVehicleId() {
      return vehicleId_;
    }

    public static final int METADATA_FIELD_NUMBER = 2;
    private volatile java.lang.Object metadata_;
    /**
     * <code>string metadata = 2;</code>
     * @return The metadata.
     */
    public java.lang.String getMetadata() {
      java.lang.Object ref = metadata_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        metadata_ = s;
        return s;
      }
    }
    /**
     * <code>string metadata = 2;</code>
     * @return The bytes for metadata.
     */
    public com.google.protobuf.ByteString
        getMetadataBytes() {
      java.lang.Object ref = metadata_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        metadata_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (vehicleId_ != 0) {
        output.writeInt32(1, vehicleId_);
      }
      if (!getMetadataBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, metadata_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (vehicleId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, vehicleId_);
      }
      if (!getMetadataBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, metadata_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof net.vbunova.grpc.VehicleService.VehicleInformationResponse)) {
        return super.equals(obj);
      }
      net.vbunova.grpc.VehicleService.VehicleInformationResponse other = (net.vbunova.grpc.VehicleService.VehicleInformationResponse) obj;

      if (getVehicleId()
          != other.getVehicleId()) return false;
      if (!getMetadata()
          .equals(other.getMetadata())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + VEHICLEID_FIELD_NUMBER;
      hash = (53 * hash) + getVehicleId();
      hash = (37 * hash) + METADATA_FIELD_NUMBER;
      hash = (53 * hash) + getMetadata().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static net.vbunova.grpc.VehicleService.VehicleInformationResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static net.vbunova.grpc.VehicleService.VehicleInformationResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static net.vbunova.grpc.VehicleService.VehicleInformationResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static net.vbunova.grpc.VehicleService.VehicleInformationResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static net.vbunova.grpc.VehicleService.VehicleInformationResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static net.vbunova.grpc.VehicleService.VehicleInformationResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static net.vbunova.grpc.VehicleService.VehicleInformationResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static net.vbunova.grpc.VehicleService.VehicleInformationResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static net.vbunova.grpc.VehicleService.VehicleInformationResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static net.vbunova.grpc.VehicleService.VehicleInformationResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static net.vbunova.grpc.VehicleService.VehicleInformationResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static net.vbunova.grpc.VehicleService.VehicleInformationResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(net.vbunova.grpc.VehicleService.VehicleInformationResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code VehicleInformationResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:VehicleInformationResponse)
        net.vbunova.grpc.VehicleService.VehicleInformationResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return net.vbunova.grpc.VehicleService.internal_static_VehicleInformationResponse_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return net.vbunova.grpc.VehicleService.internal_static_VehicleInformationResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                net.vbunova.grpc.VehicleService.VehicleInformationResponse.class, net.vbunova.grpc.VehicleService.VehicleInformationResponse.Builder.class);
      }

      // Construct using net.vbunova.grpc.VehicleService.VehicleInformationResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        vehicleId_ = 0;

        metadata_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return net.vbunova.grpc.VehicleService.internal_static_VehicleInformationResponse_descriptor;
      }

      @java.lang.Override
      public net.vbunova.grpc.VehicleService.VehicleInformationResponse getDefaultInstanceForType() {
        return net.vbunova.grpc.VehicleService.VehicleInformationResponse.getDefaultInstance();
      }

      @java.lang.Override
      public net.vbunova.grpc.VehicleService.VehicleInformationResponse build() {
        net.vbunova.grpc.VehicleService.VehicleInformationResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public net.vbunova.grpc.VehicleService.VehicleInformationResponse buildPartial() {
        net.vbunova.grpc.VehicleService.VehicleInformationResponse result = new net.vbunova.grpc.VehicleService.VehicleInformationResponse(this);
        result.vehicleId_ = vehicleId_;
        result.metadata_ = metadata_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof net.vbunova.grpc.VehicleService.VehicleInformationResponse) {
          return mergeFrom((net.vbunova.grpc.VehicleService.VehicleInformationResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(net.vbunova.grpc.VehicleService.VehicleInformationResponse other) {
        if (other == net.vbunova.grpc.VehicleService.VehicleInformationResponse.getDefaultInstance()) return this;
        if (other.getVehicleId() != 0) {
          setVehicleId(other.getVehicleId());
        }
        if (!other.getMetadata().isEmpty()) {
          metadata_ = other.metadata_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        net.vbunova.grpc.VehicleService.VehicleInformationResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (net.vbunova.grpc.VehicleService.VehicleInformationResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int vehicleId_ ;
      /**
       * <code>int32 vehicleId = 1;</code>
       * @return The vehicleId.
       */
      public int getVehicleId() {
        return vehicleId_;
      }
      /**
       * <code>int32 vehicleId = 1;</code>
       * @param value The vehicleId to set.
       * @return This builder for chaining.
       */
      public Builder setVehicleId(int value) {
        
        vehicleId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 vehicleId = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearVehicleId() {
        
        vehicleId_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object metadata_ = "";
      /**
       * <code>string metadata = 2;</code>
       * @return The metadata.
       */
      public java.lang.String getMetadata() {
        java.lang.Object ref = metadata_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          metadata_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string metadata = 2;</code>
       * @return The bytes for metadata.
       */
      public com.google.protobuf.ByteString
          getMetadataBytes() {
        java.lang.Object ref = metadata_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          metadata_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string metadata = 2;</code>
       * @param value The metadata to set.
       * @return This builder for chaining.
       */
      public Builder setMetadata(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        metadata_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string metadata = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearMetadata() {
        
        metadata_ = getDefaultInstance().getMetadata();
        onChanged();
        return this;
      }
      /**
       * <code>string metadata = 2;</code>
       * @param value The bytes for metadata to set.
       * @return This builder for chaining.
       */
      public Builder setMetadataBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        metadata_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:VehicleInformationResponse)
    }

    // @@protoc_insertion_point(class_scope:VehicleInformationResponse)
    private static final net.vbunova.grpc.VehicleService.VehicleInformationResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new net.vbunova.grpc.VehicleService.VehicleInformationResponse();
    }

    public static net.vbunova.grpc.VehicleService.VehicleInformationResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<VehicleInformationResponse>
        PARSER = new com.google.protobuf.AbstractParser<VehicleInformationResponse>() {
      @java.lang.Override
      public VehicleInformationResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new VehicleInformationResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<VehicleInformationResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<VehicleInformationResponse> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public net.vbunova.grpc.VehicleService.VehicleInformationResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_VehicleInformationRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_VehicleInformationRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_VehicleInformationResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_VehicleInformationResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024vehicleService.proto\"\033\n\031VehicleInforma" +
      "tionRequest\"A\n\032VehicleInformationRespons" +
      "e\022\021\n\tvehicleId\030\001 \001(\005\022\020\n\010metadata\030\002 \001(\t2b" +
      "\n\016vehicleService\022P\n\025getVehicleInformatio" +
      "n\022\032.VehicleInformationRequest\032\033.VehicleI" +
      "nformationResponseB\022\n\020net.vbunova.grpcb\006" +
      "proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_VehicleInformationRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_VehicleInformationRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_VehicleInformationRequest_descriptor,
        new java.lang.String[] { });
    internal_static_VehicleInformationResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_VehicleInformationResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_VehicleInformationResponse_descriptor,
        new java.lang.String[] { "VehicleId", "Metadata", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
